# Generated by Django 5.2.3 on 2025-08-10 15:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0002_add_session_id_deduplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercustomization',
            name='is_initialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OnboardingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(choices=[('3-4', '3-4 years'), ('5-6', '5-6 years'), ('7-9', '7-9 years'), ('10+', '10+ years')], max_length=10)),
                ('primary_language', models.CharField(default='English', max_length=50)),
                ('goals', models.JSONField(default=list)),
                ('interests', models.JSONField(default=list)),
                ('daily_goal_minutes', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)])),
                ('voice_preference', models.CharField(choices=[('kid', 'Kid voice'), ('soft', 'Soft & friendly'), ('neutral', 'Neutral')], default='kid', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
