# Generated by Django 5.2.3 on 2025-08-11 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0004_userprofile_has_active_avatar_useravatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='total_speaking_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
