# Generated by Django 5.2.3 on 2025-08-23 10:14

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0005_alter_userprofile_total_speaking_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('elevenlabs_conversation_id', models.CharField(max_length=255, unique=True)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('user_messages_count', models.IntegerField(default=0)),
                ('ai_responses_count', models.IntegerField(default=0)),
                ('topics_covered', models.JSONField(default=list)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('engagement_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('speech_clarity_notes', models.TextField(blank=True)),
                ('improvements_noted', models.JSONField(default=list)),
                ('areas_to_work_on', models.JSONField(default=list)),
                ('experience_earned', models.IntegerField(default=0)),
                ('session_rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('preference', 'User Preference'), ('achievement', 'Achievement Milestone'), ('challenge', 'Ongoing Challenge'), ('interest', 'Personal Interest'), ('goal', 'Learning Goal'), ('feedback', 'Feedback Response')], max_length=20)),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('importance_score', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('last_referenced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'memory_type'], name='therapy_use_user_id_3e4b51_idx'), models.Index(fields=['user', 'importance_score'], name='therapy_use_user_id_a3399b_idx')],
                'unique_together': {('user', 'key')},
            },
        ),
    ]
